#!/usr/bin/env ruby
#
# Eric Radman <ericshane@eradman.com> 2019

require 'json'

def usage
  $stderr.puts "usage: flattenjs < input"
  exit(1)
end

color = $stdout.isatty
usage if ARGV.pop
usage if $stdin.isatty

json_in = ""
while path = $stdin.gets
  json_in << path
end

h = JSON.parse(json_in)

# from https://stackoverflow.com/a/10715242/1809872
module Enumerable
  def flatten_with_path(parent_prefix = nil)
    res = {}

    self.each_with_index do |elem, i|
      if elem.is_a?(Array)
        k, v = elem
      else
        k, v = i, elem
      end

      # assign key name for result hash
      key = parent_prefix ? "#{parent_prefix},#{k}" : k

      if v.is_a? Enumerable
        # recursive call to flatten child elements
        res.merge!(v.flatten_with_path(key))
      else
        res[key] = v
      end
    end

    res
  end
end

h.flatten_with_path.each do |path, value|
  if color
    puts "{#{path}} \e[37m#{value}\e[39m"
  else
    puts "{#{path}} #{value}"
  end
end

