.\"
.\" Copyright (c) 2012 Eric Radman <ericshane@eradman.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd January 20, 2015
.Dt PG_TMP 1
.Os
.Sh NAME
.Nm pg_tmp
.Nd spin up temporary PostgreSQL database
.Sh SYNOPSIS
.Nm pg_tmp
.Op Fl w Ar timeout
.Op Fl t
.Sh DESCRIPTION
The
.Nm
utility is used for spinning up a temporary PostgreSQL database for use in
automated testing.
A URI to the new database is printed to
.Dv STDOUT .
.Pp
Temporary databases are automatically shutdown and garbage collected after 60
seconds or the specified
.Ar timeout .
If one or more clients are still connected then
.Nm
sleeps and retries again after the same interval.
.Pp
Several tactics are used reduce the wait time for a new database to less than
one second.
.Nm
spawns a background process that initializes a new database under
.Pa /tmp/ephemeralpg.XXXXXX
which is picked up by subsequent invocations.
.Pp
By default a Unix socket is returned.
The
.Fl t
flag changes this to 127.0.0.1 with a port selected by
.Xr getsocket 1 .
.Sh EXAMPLES
Create a temporary database and run a query:
.Bd -literal -offset indent
uri=$(pg_tmp)
psql $uri -f my.sql
.Ed
.Sh SEE ALSO
.Xr mktemp 1 ,
.Xr pg_ctl 1
.Sh CAVEATS
Concurrent use of multiple major versions of PostgreSQL is not supported.
