.\"
.\" Copyright (c) 2014 Eric Radman <ericshane@eradman.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd March 27, 2019
.Dt PG_TMP 1
.Os
.Sh NAME
.Nm pg_tmp
.Nd quickly spin up temporary PostgreSQL database
.Sh SYNOPSIS
.Nm pg_tmp
.Op Fl k
.Op Fl t Op Fl p Ar port
.Op Fl w Ar timeout
.Op Fl o Ar extra-options
.Op Fl d Ar datadir
.Sh DESCRIPTION
The
.Nm
utility creates a temporary instance of PostgreSQL and prints the connection URL
to standard output.
.Nm
spawns a background process that initializes a new database under
.Pa /tmp/ephemeralpg.*/${PGVER}
which is used by subsequent invocations to reduce startup time.
The arguments are as follows:
.Bl -tag -width Ds
.It Fl k
Keep the temporary directory after the server is shut down.
.It Fl w
Shut down and remove the database after the specified
.Ar timeout .
If one or more clients are still connected then
.Nm
sleeps and retries again after the same interval.
A value of 0 will leave the server running indefinitely.
The default is 60 seconds.
.It Fl t
Use a TCP port selected by
.Xr getsocket 1
bound to 127.0.0.1.
A port may be selected using the
.Fl p
flag.
Otherwise the path to a Unix socket is returned.
.It Fl o
Specifies extra-options to be passed directly to the
.Xr postgres 1
binary.
These options should usually be surrounded by quotes to ensure that they are
passed through as a group.
.It Fl d
Specify the temporary directory to use.
May be used with the optional arguments
.Ar initdb ,
.Ar start
and is required for
.Ar stop .
If this option is used
.Nm
will not initialize a new database for subsequent invocations use.
.El
.Sh ENVIRONMENT
.Bl -tag -width TMPDIR
.It Ev TMPDIR
base directory in which to create and run the ephemeral instances of
.Xr postgres 1
.El
.Sh EXAMPLES
Create a temporary database and run a query:
.Bd -literal -offset indent
uri=$(pg_tmp)
psql $uri -f my.sql
.Ed
.Pp
Start a temporary server with a custom extension:
.Bd -literal -offset indent
uri=$(pg_tmp -o "-c shared_preload_libraries=$PWD/auth_hook")
psql $uri -c "SELECT 1"
.Ed
.Sh SEE ALSO
.Xr pg_ctl 1
